version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004-cuda-11.4:202110-01
    resource_class: gpu.nvidia.small
    steps:
      - checkout      
      - run:
          name: install Rustup
          command: |
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path --default-toolchain stable
            source "$HOME"/.cargo/env
            echo 'source $HOME/.cargo/env' >> $BASH_ENV
      - run: cargo --version
      - run: nvidia-smi
